[build]
  base = ""
  publish = "dist/project"  # Make sure this is where your build output goes
  command = "npm run build --prod"  # Use Angular's build script to generate the production build

[dev]
  command = "ng serve --open"
  port = 3000
  status = 200
